/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PodInfoApplyConfiguration represents a declarative configuration of the PodInfo type for use
// with apply.
//
// PodInfo contains a set of information related to the Pod running the Camel application.
type PodInfoApplyConfiguration struct {
	// the Pod name
	Name *string `json:"name,omitempty"`
	// the Pod ip
	InternalIP *string `json:"internalIp,omitempty"`
	// the Pod status
	Status *string `json:"status,omitempty"`
	// the Pod updtime timestamp
	UptimeTimestamp *v1.Time `json:"uptimeTimestamp,omitempty"`
	// the Pod readiness
	Ready *bool `json:"ready,omitempty"`
	// the Pod reason why it's not ready
	Reason *string `json:"reason,omitempty"`
	// Observability services information
	ObservabilityService *ObservabilityServiceInfoApplyConfiguration `json:"observe,omitempty"`
	// Some information about the Camel runtime
	Runtime *RuntimeInfoApplyConfiguration `json:"runtime,omitempty"`
	// the Pod exposes the jolokia port
	JolokiaEnabled *bool `json:"jolokiaEnabled,omitempty"`
}

// PodInfoApplyConfiguration constructs a declarative configuration of the PodInfo type for use with
// apply.
func PodInfo() *PodInfoApplyConfiguration {
	return &PodInfoApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithName(value string) *PodInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithInternalIP sets the InternalIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InternalIP field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithInternalIP(value string) *PodInfoApplyConfiguration {
	b.InternalIP = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithStatus(value string) *PodInfoApplyConfiguration {
	b.Status = &value
	return b
}

// WithUptimeTimestamp sets the UptimeTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UptimeTimestamp field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithUptimeTimestamp(value v1.Time) *PodInfoApplyConfiguration {
	b.UptimeTimestamp = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithReady(value bool) *PodInfoApplyConfiguration {
	b.Ready = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithReason(value string) *PodInfoApplyConfiguration {
	b.Reason = &value
	return b
}

// WithObservabilityService sets the ObservabilityService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservabilityService field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithObservabilityService(value *ObservabilityServiceInfoApplyConfiguration) *PodInfoApplyConfiguration {
	b.ObservabilityService = value
	return b
}

// WithRuntime sets the Runtime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Runtime field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithRuntime(value *RuntimeInfoApplyConfiguration) *PodInfoApplyConfiguration {
	b.Runtime = value
	return b
}

// WithJolokiaEnabled sets the JolokiaEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JolokiaEnabled field is set to the value of the last call.
func (b *PodInfoApplyConfiguration) WithJolokiaEnabled(value bool) *PodInfoApplyConfiguration {
	b.JolokiaEnabled = &value
	return b
}
