/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	camelv1alpha1 "github.com/camel-tooling/camel-dashboard-operator/pkg/apis/camel/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SLIExchangeSuccessRateApplyConfiguration represents a declarative configuration of the SLIExchangeSuccessRate type for use
// with apply.
//
// SLIExchangeSuccessRate contains the information related to the SLI.
type SLIExchangeSuccessRateApplyConfiguration struct {
	// the success percentage
	SuccessPercentage *string `json:"successPercentage,omitempty"`
	// the interval time considered
	SamplingIntervalDuration *time.Duration `json:"samplingInterval,omitempty"`
	// the total exchanges in the interval time considered
	SamplingIntervalTotal *int `json:"samplingIntervalTotal,omitempty"`
	// the failed exchanges in the interval time considered
	SamplingIntervalFailed *int `json:"samplingIntervalFailed,omitempty"`
	// the last message timestamp
	LastTimestamp *v1.Time `json:"lastTimestamp,omitempty"`
	// a human readable status information
	Status *camelv1alpha1.SLIExchangeStatus `json:"status,omitempty"`
}

// SLIExchangeSuccessRateApplyConfiguration constructs a declarative configuration of the SLIExchangeSuccessRate type for use with
// apply.
func SLIExchangeSuccessRate() *SLIExchangeSuccessRateApplyConfiguration {
	return &SLIExchangeSuccessRateApplyConfiguration{}
}

// WithSuccessPercentage sets the SuccessPercentage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessPercentage field is set to the value of the last call.
func (b *SLIExchangeSuccessRateApplyConfiguration) WithSuccessPercentage(value string) *SLIExchangeSuccessRateApplyConfiguration {
	b.SuccessPercentage = &value
	return b
}

// WithSamplingIntervalDuration sets the SamplingIntervalDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplingIntervalDuration field is set to the value of the last call.
func (b *SLIExchangeSuccessRateApplyConfiguration) WithSamplingIntervalDuration(value time.Duration) *SLIExchangeSuccessRateApplyConfiguration {
	b.SamplingIntervalDuration = &value
	return b
}

// WithSamplingIntervalTotal sets the SamplingIntervalTotal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplingIntervalTotal field is set to the value of the last call.
func (b *SLIExchangeSuccessRateApplyConfiguration) WithSamplingIntervalTotal(value int) *SLIExchangeSuccessRateApplyConfiguration {
	b.SamplingIntervalTotal = &value
	return b
}

// WithSamplingIntervalFailed sets the SamplingIntervalFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplingIntervalFailed field is set to the value of the last call.
func (b *SLIExchangeSuccessRateApplyConfiguration) WithSamplingIntervalFailed(value int) *SLIExchangeSuccessRateApplyConfiguration {
	b.SamplingIntervalFailed = &value
	return b
}

// WithLastTimestamp sets the LastTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTimestamp field is set to the value of the last call.
func (b *SLIExchangeSuccessRateApplyConfiguration) WithLastTimestamp(value v1.Time) *SLIExchangeSuccessRateApplyConfiguration {
	b.LastTimestamp = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *SLIExchangeSuccessRateApplyConfiguration) WithStatus(value camelv1alpha1.SLIExchangeStatus) *SLIExchangeSuccessRateApplyConfiguration {
	b.Status = &value
	return b
}
