/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	camelv1 "github.com/squakez/camel-dashboard-operator/pkg/apis/camel/v1"
)

// IntegrationStatusApplyConfiguration represents a declarative configuration of the IntegrationStatus type for use
// with apply.
type IntegrationStatusApplyConfiguration struct {
	Phase *camelv1.IntegrationPhase `json:"phase,omitempty"`
}

// IntegrationStatusApplyConfiguration constructs a declarative configuration of the IntegrationStatus type for use with
// apply.
func IntegrationStatus() *IntegrationStatusApplyConfiguration {
	return &IntegrationStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *IntegrationStatusApplyConfiguration) WithPhase(value camelv1.IntegrationPhase) *IntegrationStatusApplyConfiguration {
	b.Phase = &value
	return b
}
